---
title: "ESM 244 Lab Week 2"
author: "Roni Shen"
date: "1/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

# for PCA:
library(ggfortify)

# for ggplot customization:
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# to make compound figures:
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% 
    # select columns that end with "_mm"
  drop_na() %>% 
  scale() %>% 
    # scales variable values for disparate units
  prcomp()

# look at loadings of variables
penguin_pca$rotation

# create new dataset that contain original variables to change aes() of graph based on other variables
penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

# create biplot using autoplot to recognize type of graph
autoplot(penguin_pca,
         data = penguin_complete,
         colour = 'species',
         loadings = TRUE,
         loadings.label = TRUE) +
  theme_minimal() # can customize like you would a ggplot

# interpret graph: PC1 and PC2 capture almost 90% of variance in data
```

### Part 2: ggplot2 customization and reading in different file types


